#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';

use if $conf::lib, lib => qw($conf::lib);
use Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

unless ( $bot->logged_in ) {
	$bot->login( $conf::user, $conf::pass );
}

my ($page, $content, $summary) = @ARGV;
$summary = $content unless defined $summary;

my $ret;
$ret = $bot->put( $page, $content, $summary ) while not $ret;
