#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';
unshift @INC, $conf::lib if $conf::lib;
require Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

$bot->login( $conf::user, $conf::pass ) unless $bot->logged_in;

my ($page, $content, $summary) = @ARGV;
$summary = $content unless defined $summary;

my $ret;
$ret = $bot->put( $page, $content, $summary ) while not $ret;
