#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratoolsconf';

use if $conf::lib, lib => qw($conf::lib);
use Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

unless ( $bot->logged_in ) {
	print "Logging in...";
	$bot->login( $conf::user, $conf::pass );
	print "done\n";
}

my ($pages, $reason) = @ARGV;
$reason = '' unless defined $reason;

for my $page (split /\|/, $pages) {
	print "Deleting '$page'...";
	print $bot->delete( $page, $reason ) ? "done\n" : "fuck\n";
}
