#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';
unshift @INC, $conf::lib if $conf::lib;
require Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

$bot->login( $conf::user, $conf::pass ) unless $bot->logged_in;

my ($pages, $reason) = @ARGV;
$reason = '' unless defined $reason;

my $ret;
for my $page (split /\|/, $pages) {
	$ret = $bot->delete( $page, $reason ) while not $ret;
	$ret = undef;
}
