#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';

use if $conf::lib, lib => qw($conf::lib);
use Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

unless ( $bot->logged_in ) {
	$bot->login( $conf::user, $conf::pass );
}

my ($pages, $reason) = @ARGV;
$reason = '' unless defined $reason;

my $ret;
for my $page (split /\|/, $pages) {
	$ret = $bot->delete( $page, $reason ) while not $ret;
	$ret = undef;
}
