#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';

use if $conf::lib, lib => qw($conf::lib);
use Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

unless ( $bot->logged_in ) {
	$bot->login( $conf::user, $conf::pass );
}

my ($froms, $to) = @ARGV;

my $ret;
for my $from (split /\|/, $froms) {
	$ret = $bot->put( $from, "#tilvísun [[$to]]" , "Tilvísun: [[$from]] => [[$to]]", minor => 1 ) while not $ret;
	$ret = undef;
}
