#!/usr/bin/env perl
use strict;

require $ENV{HOME} . '/.anuratools.conf';
unshift @INC, $conf::lib if $conf::lib;
require Net::Anura;

my $bot = Net::Anura->new(
	wiki => $conf::wiki
);

$bot->login( $conf::user, $conf::pass ) unless $bot->logged_in;

my ($froms, $to) = @ARGV;

my $ret;
for my $from (split /\|/, $froms) {
	$ret = $bot->put( $from, "#tilvísun [[$to]]" , "Tilvísun: [[$from]] => [[$to]]", minor => 1 ) while not $ret;
	$ret = undef;
}
